name: gulls
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - cmake
  - gsl
  - cfitsio
  - compilers
  - matplotlib
  - pandas
  - astropy
  - numpy
  - sphinx
  - sphinx_rtd_theme
  - pip
  - pip:
      - VBMicrolensing
